### ISSUE TITLE
Botostubs doesn't know about bucket.upload_file[obj]()

### ISSUE THREAD

**Issue by major-mayer** [jeshan/botostubs#15]
I created a S3 bucket ressource with the boto3 library and annotated it with type hints.
From the S3 resource i generated an bucket object.
The auto-completion does seem to work just fine, apart from the methods `upload_file[obj]()` and `download_file[obj]()`, which is simply not existent on the bucket object:

![grafik](https://user-images.githubusercontent.com/17907799/102770367-51ad7b80-4384-11eb-9daf-524c81463cea.png)

The other methods are there:
![grafik](https://user-images.githubusercontent.com/17907799/102770423-6be75980-4384-11eb-9002-be8a617b363f.png)

Here is the documentation of this method.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html?highlight=upload_file#S3.Bucket.upload_fileobj

**Comment by jeshan** [comment]
Thank you for reporting. I'm looking into it.

**Comment by jeshan** [comment]
A fix will be out soon on the regular schedule (midnight UTC). Look out for a new 0.13.x release.

**Comment by major-mayer** [comment]
Nice, thanks for the really quick fix 👍👍

**Comment by jeshan** [comment]
My pleasure.. but it turns out that I wrongly implemented the fix! So, I've just released a 0.14.x.

Here's what it will look like now (in Intellij):

![image](https://user-images.githubusercontent.com/1020565/102875133-d2d84180-445c-11eb-921f-87de9cee4388.png)

Thanks to your report, I've found that this needs to be done for `ec2`, `s3`, and `dynamodb`.

**Comment by major-mayer** [comment]
Again thanks for your work. It's working now! I just tried it out using VSCode and i get the right autocompletion :heart:
